In [1]:
from pathlib import Path
import pandas as pd

base = Path("../data/raw/monitoring_2026-05-21_2026-06-20")

noise_files = list(base.rglob("*Zaj.xlsx"))
water_files = list(base.rglob("*Felszin_alatti_viz.xlsx"))

print(f"Noise files: {len(noise_files)}")
print(f"Water files: {len(water_files)}")

Noise files: 0
Water files: 0

In [3]:
from pathlib import Path
import pandas as pd

base = Path("../data/raw/monitoring_2026-05-21_2026-06-19")

noise_files = list(base.rglob("*_Zaj.xlsx"))
water_files = list(base.rglob("*_Felszin_alatti_viz.xlsx"))

print(f"Noise files: {len(noise_files)}")
print(f"Water files: {len(water_files)}")

Noise files: 5
Water files: 15

In [4]:
noise_df = pd.read_excel(noise_files[0])
water_df = pd.read_excel(water_files[0])

print("Noise columns:")
print(noise_df.columns.tolist())

print("\nWater columns:")
print(water_df.columns.tolist())

display(noise_df.head())

display(water_df.head())

C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Noise columns:
['timestamp', 'Location', 'Mérőeszköz', 'érték', 'mértékegység']

Water columns:
['timestamp', 'Location', 'Mérőeszköz', 'érték', 'mértékegység']

,timestamp,Location,Mérőeszköz,érték,mértékegység
0,2026-05-21-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,58.9,dB
1,2026-05-21-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ éjszakai,50.3,dB
2,2026-05-22-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,63.4,dB
3,2026-05-22-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ éjszakai,50.9,dB
4,2026-05-23-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,58.7,dB

,timestamp,Location,Mérőeszköz,érték,mértékegység
0,2026-05-21-02-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",Conductivity,1.1,mS/cm
1,2026-05-21-02-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",WaterLevel,7.0,m
2,2026-05-21-02-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",WaterTemp,12.7,celsius
3,2026-05-21-03-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",Conductivity,1.1,mS/cm
4,2026-05-21-03-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",WaterLevel,7.0,m

In [5]:
noise_all = pd.concat(
    [pd.read_excel(f) for f in noise_files],
    ignore_index=True,
)

print("Noise records:", len(noise_all))
print("Stations:", noise_all["Location"].nunique())

display(noise_all.head())

C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Noise records: 300
Stations: 5

,timestamp,Location,Mérőeszköz,érték,mértékegység
0,2026-05-21-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,58.9,dB
1,2026-05-21-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ éjszakai,50.3,dB
2,2026-05-22-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,63.4,dB
3,2026-05-22-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ éjszakai,50.9,dB
4,2026-05-23-00-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,58.7,dB

In [6]:
water_all = pd.concat(
    [pd.read_excel(f) for f in water_files],
    ignore_index=True,
)

print("Water records:", len(water_all))
print("Stations:", water_all["Location"].nunique())

display(water_all.head())

C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\smsad\OneDrive\Desktop\greenmind-ai\backend\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Water records: 31625
Stations: 15

,timestamp,Location,Mérőeszköz,érték,mértékegység
0,2026-05-21-02-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",Conductivity,1.1,mS/cm
1,2026-05-21-02-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",WaterLevel,7.0,m
2,2026-05-21-02-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",WaterTemp,12.7,celsius
3,2026-05-21-03-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",Conductivity,1.1,mS/cm
4,2026-05-21-03-00,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",WaterLevel,7.0,m

In [7]:
noise_clean = noise_all.rename(
    columns={
        "Mérőeszköz": "measurement_type",
        "érték": "value",
        "mértékegység": "unit",
        "Location": "location",
    }
)

noise_clean["timestamp"] = pd.to_datetime(
    noise_clean["timestamp"],
    format="%Y-%m-%d-%H-%M",
)

noise_clean["value"] = pd.to_numeric(
    noise_clean["value"],
    errors="coerce",
)

print(noise_clean.dtypes)

display(noise_clean.head())

timestamp           datetime64[us]
location                       str
measurement_type               str
value                      float64
unit                           str
dtype: object

,timestamp,location,measurement_type,value,unit
0,2026-05-21,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,58.9,dB
1,2026-05-21,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ éjszakai,50.3,dB
2,2026-05-22,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,63.4,dB
3,2026-05-22,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ éjszakai,50.9,dB
4,2026-05-23,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",LAEQ nappali,58.7,dB

In [8]:
noise_clean["measurement_type"].value_counts()

measurement_type
LAEQ nappali     150
LAEQ éjszakai    150
Name: count, dtype: int64

In [9]:
noise_clean.groupby("measurement_type")["value"].describe()

                  count       mean       std   min   25%    50%     75%   max
measurement_type
LAEQ nappali      150.0  56.570667  3.758383  50.4  53.7  56.05  59.175  67.7
LAEQ éjszakai     150.0  48.915333  4.106661  42.7  45.1  48.15  51.700  62.1

In [10]:
water_clean = water_all.rename(
    columns={
        "Mérőeszköz": "measurement_type",
        "érték": "value",
        "mértékegység": "unit",
        "Location": "location",
    }
)

water_clean["timestamp"] = pd.to_datetime(
    water_clean["timestamp"],
    format="%Y-%m-%d-%H-%M",
)

water_clean["value"] = pd.to_numeric(
    water_clean["value"],
    errors="coerce",
)

print(water_clean["measurement_type"].value_counts())

display(
    water_clean.groupby("measurement_type")["value"].describe()
)

measurement_type
WaterLevel      10542
WaterTemp       10542
Conductivity    10541
Name: count, dtype: int64

                    count       mean       std   min   25%   50%   75%   max
measurement_type
Conductivity      10541.0   1.385001  0.764687   0.2   0.9   1.1   2.1   3.2
WaterLevel        10542.0   5.340211  2.933448   1.4   3.2   4.0   6.9  13.7
WaterTemp         10542.0  13.540211  1.299066  11.8  12.8  13.1  14.0  16.7

In [12]:
air_locations = sorted(
    pd.read_csv(
        "../data/processed/air_measurements_cleaned.csv"
    )["location"].dropna().unique()
)

noise_locations = sorted(
    noise_clean["location"].dropna().unique()
)

water_locations = sorted(
    water_clean["location"].dropna().unique()
)

locations = pd.DataFrame({
    "Air": pd.Series(air_locations),
    "Noise": pd.Series(noise_locations),
    "Water": pd.Series(water_locations),
})

display(locations)

,Air,Noise,Water
0,"Angyalföld tér 4. (47.52506265, 21.60358902)","Debrecen, Szávay Gyula street Idősek otthona (...","Angyalföld tér 4. (47.52506265, 21.60358902)"
1,DGÖ 481-47 kereszteződés nyugati sarok (47.461...,"Mikepércs, Rózsás utca (47.44742297, 21.63063962)",DGÖ 481-47 kereszteződés nyugati sarok (47.461...
2,"Debrecen, Bem tér 18/C, ATOMKI (47.54361985, 2...","Szepes, Sárga dűlő (47.46442193, 21.58860163)","Debrecen, Bem tér 18/C, ATOMKI (47.54361985, 2..."
3,"Debrecen, Benczúr Gyula u. 5 (47.56103507, 21....","ÉNYGÖ, BMW körút (47.577175, 21.502204)","Debrecen, Benczúr Gyula u. 5 (47.56103507, 21...."
4,"Debrecen, Szávay Gyula street Idősek otthona (...","ÉNYGÖ, M35 Józsa új csomópont (47.59067666, 21...","Debrecen, Szávay Gyula street Idősek otthona (..."
5,Debrecen-Haláp Hármashegy Erdei Iskola (47.558...,NaN,Debrecen-Haláp Hármashegy Erdei Iskola (47.558...
6,"Debrecen-Józsa, Klastrompart sor, játszótér (4...",NaN,"Debrecen-Józsa, Klastrompart sor, játszótér (4..."
7,"Karácsony György utcai bölcsőde (47.53312747, ...",NaN,"Karácsony György utcai bölcsőde (47.53312747, ..."
8,"Mikepércs, Rózsás utca (47.44742297, 21.63063962)",NaN,"Mikepércs, Rózsás utca (47.44742297, 21.63063962)"
9,"Petőfi tér (47.52324542, 21.6337404)",NaN,"Petőfi tér (47.52324542, 21.6337404)"
10,"Szabó Pál utca 59 (47.54820104, 21.66937425)",NaN,"Szabó Pál utca 59 (47.54820104, 21.66937425)"
11,"Szepes, Sárga dűlő (47.46442193, 21.58860163)",NaN,"Szepes, Sárga dűlő (47.46442193, 21.58860163)"
12,"Sétakert utca 1-3 (47.54547049, 21.61669657)",NaN,"Sétakert utca 1-3 (47.54547049, 21.61669657)"
13,"Vezér úti Víztározó (47.55757175, 21.59611899)",NaN,"Vezér úti Víztározó (47.55757175, 21.59611899)"
14,"ÉNYGÖ, BMW körút (47.577175, 21.502204)",NaN,"ÉNYGÖ, BMW körút (47.577175, 21.502204)"
15,"ÉNYGÖ, M35 Józsa új csomópont (47.59067666, 21...",NaN,NaN

In [13]:
noise_clean.to_csv("../data/processed/noise_measurements_cleaned.csv", index=False)

water_clean.to_csv("../data/processed/water_measurements_cleaned.csv", index=False)